### ISSUE TITLE
Adding new Balance Adjustment doesnt validate first, so invalid data will crash app

### ISSUE THREAD

**Issue by Benrnz** [Benrnz/BudgetAnalyser#60]

**Comment by Benrnz** [comment]
at BudgetAnalyser.Engine.Services.LedgerService.CreateBalanceAdjustment(LedgerEntryLine entryLine, Decimal amount, String narrative, AccountType account) in c:\Development\GitRepositories\BudgetAnalyserProject\Trunk\BudgetAnalyser.Engine\Services\LedgerService.cs:line 75
   at BudgetAnalyser.LedgerBook.LedgerTransactionsController.SaveBalanceAdjustment() in c:\Development\GitRepositories\BudgetAnalyserProject\Trunk\BudgetAnalyser\LedgerBook\LedgerTransactionsController.cs:line 335
   at BudgetAnalyser.LedgerBook.LedgerTransactionsController.Save() in c:\Development\GitRepositories\BudgetAnalyserProject\Trunk\BudgetAnalyser\LedgerBook\LedgerTransactionsController.cs:line 322
   at BudgetAnalyser.LedgerBook.LedgerTransactionsController.OnAddNewTransactionCommandExecuted() in c:\Development\GitRepositories\BudgetAnalyserProject\Trunk\BudgetAnalyser\LedgerBook\LedgerTransactionsController.cs:line 212

**Comment by Benrnz** [comment]
at BudgetAnalyser.Engine.Services.LedgerService.CreateBalanceAdjustment(LedgerEntryLine entryLine, Decimal amount, String narrative, AccountType account) in c:\Development\GitRepositories\BudgetAnalyserProject\Trunk\BudgetAnalyser.Engine\Services\LedgerService.cs:line 75
   at BudgetAnalyser.LedgerBook.LedgerTransactionsController.SaveBalanceAdjustment() in c:\Development\GitRepositories\BudgetAnalyserProject\Trunk\BudgetAnalyser\LedgerBook\LedgerTransactionsController.cs:line 335
   at BudgetAnalyser.LedgerBook.LedgerTransactionsController.Save() in c:\Development\GitRepositories\BudgetAnalyserProject\Trunk\BudgetAnalyser\LedgerBook\LedgerTransactionsController.cs:line 322
   at BudgetAnalyser.LedgerBook.LedgerTransactionsController.OnAddNewTransactionCommandExecuted() in c:\Development\GitRepositories\BudgetAnalyserProject\Trunk\BudgetAnalyser\LedgerBook\LedgerTransactionsController.cs:line 212
